### ISSUE TITLE
Creating project with no name throws PHP error but still creates a project with no name

### ISSUE THREAD

**Issue by arlelommel** [multidimensionalquality/qt21-scorecard#14]
If a project is created with no name filled in, it throws the following error:

Notice: Uninitialized string offset: 0 in /local/scorecard-demo.qt21.eu/site/src/DFKI/ScorecardBundle/Services/ProjectService.php on line 222

But it still makes the project.

Solution is to add some Javascript validation to make sure there is a name before creating a project.

**Comment by jnehring** [comment]
fixed but not pushed to live.

**Comment by jnehring** [comment]
pushed to live
