### ISSUE TITLE
User management is missing way to reset password

### ISSUE THREAD

**Issue by arlelommel** [multidimensionalquality/qt21-scorecard#26]
Users currently cannot reset passwords. We should look at a more robust password management framework or at exposing better controls.

**Comment by jnehring** [comment]
Did you try the [edit profile](http://www.qt21.eu/scorecard/profile/edit) page? There should be a way to change your password on that page. The dialog is not nicely formated so I raised #27.

**Comment by jnehring** [comment]
After a discussion on Skype I moved this issue to #28 and #29
