### ISSUE TITLE
Crash with 500 error for some metrics files

### ISSUE THREAD

**Issue by arlelommel** [multidimensionalquality/qt21-scorecard#6]
The Scorecard inconsistency crashes without explanatory error (with a 500 Internal Server error) for some metrics files.

**Comment by jnehring** [comment]
Please send me the metric files. You can also upload the metric files in the "data" folder on github and link them here in the issue.

**Comment by jnehring** [comment]
We have better error reporting now. I close the old issue because I think not much is going to happen here.
